services:
  - type: web
    name: baisoft
    region: oregon
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: "sh -c 'cd backend && gunicorn config.wsgi --bind 0.0.0.0:$PORT'"
    envVars:
      - key: PYTHON_VERSION
        value: "3.14.3"
      - key: SECRET_KEY
        value: "django-insecure-change-this-in-production"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "baisoft.onrender.com"
