services:
  - type: web
    name: baisoft
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: "3.14.3"
